### ISSUE TITLE
The translations directory does not exist. 

### ISSUE THREAD

**Issue by clicktrend** [tstoeckler/drupal-site-template#1]
Create writable directory

```
sites/default/files/translations
```

because the installation script requires it.

Maybe ist should be added to .gitignore.

**Comment by tstoeckler** [comment]
Thanks for bringing this up!

I just committed 94187091ad86f64b4135ec9f382ecaa18ed87b88 which creates a `sites/default/files` directory. This allows the installer to create the `translations` directory.

And also added this to `.gitignore` in c92965fecea4c93c8c17d5dac33a1711be6f5887.

Thus, closing this. Please reopen if this does not work for you.
