### ISSUE TITLE
Drush error 

### ISSUE THREAD

**Issue by Palashvijay4O** [tstoeckler/drupal-site-template#4]
Drush 5.10.0 does not support Drupal . Use Drush 4 instead.         [error]
PHP Fatal error:  Class 'Drupal' not found in /var/www/html/drupal-8.0.x-dev/core/includes/bootstrap.inc on line 171
Drush command terminated abnormally due to an unrecoverable error.                                                                                             [error]
Error: Class 'Drupal' not found in /var/www/html/drupal-8.0.x-dev/core/includes/bootstrap.inc, line 171

When I try to run drush with drupal-8 dev release the above error messages come .
How to fix all this ?

**Comment by tstoeckler** [comment]
You need latest Drush to use the site template, i.e. master branch.

You can also just use the "local" Drush version provided by the template, i.e. in the web directory do `../vendor/bin/drush`.

Please re-open if you have additional questions/problems but closing this for now.

**Comment by Palashvijay4O** [comment]
There is no directory named drush in core/vendor/bin .

**Comment by tstoeckler** [comment]
No there isn't :-)

When you clone this repository you need to run `composer install` in its root. Then there will be a `vendor` directory in the root (as well as a `web/core/vendor` directory). The former has a `bin/drush`.
